apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Chart.Name }}-status-reporter"
spec:
  schedule: "{{ .Values.shortLivedTaskMinutes }} * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: "topic-config-volume"
            configMap:
              name: "{{ .Chart.Name }}-topic-config"
          restartPolicy: OnFailure
          containers:
          - name: {{ .Chart.Name }}
          {{- if eq .Values.image.tag "latest" }}
            image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.Version .Values.image.tag }}"
          {{- else }}
            image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:v{{ default .Chart.Version .Values.image.tag }}"
          {{- end }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              - soak-clients
              - report
            env:
              - name: TROGDOR_HOST
                value: "http://cc-trogdor-service-coordinator.{{.Release.Namespace}}.svc:{{ .Values.trogdorCoordinatorPort }}"
              - name: TROGDOR_TOPIC_CONFIG_PATH
                value: "{{ .Values.topicConfigPath }}"
              - name: DEBUG_LOGS
                value: "{{ .Values.debugLogs }}"
            volumeMounts:
              - name: topic-config-volume
                mountPath: /mnt/config/topic
