# Default values for trogdor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

coordinatorReplicaCount: 1
agentReplicaCount: 6

image:
  repository: confluent-docker.jfrog.io/confluentinc
  name: cc-trogdor
  tag: 0.109.0-2.3.0-SNAPSHOT
  pullPolicy: Always

kafkaName: kafka

trogdorAgentPort: 9001
trogdorCoordinatorPort: 9002
trogdorJmxPort: 7203

service:
  type: NodePort
  port: 8889

resources: {}

nodeSelector: {}

tolerations: []

agentAffinity: []
